version: '3.3'
name: "MySql-5.7"
services:
  mySQL:
    image: mysql:5.7
    container_name: mysql-5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'gioliveira'
      MYSQL_PASSWORD: 'neo@12345'
      MYSQL_ROOT_PASSWORD: 'neo@12345'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - D:\DockerCompose\MySQLVolumes:/var/lib/mysql