version: '3'
services:
  oracle:
    image: oracle/database:21.3.0-ee
    container_name: oracle-21c
    environment:
      ORACLE_PDB: orcl
      ORACLE_PWD: Ja0103e
      INIT_SGA_SIZE: 3000
      INIT_PGA_SIZE: 1000
    ports:
      - "1521:1521"
      - "5500:5500"
    volumes:
      - D:\DockerCompose\OracleVolume21c:/opt/oracle/oradata
  mysql:
    image: mysql:5.7
    container_name: mysql-5.7
    environment:
      MYSQL_ROOT_PASSWORD: Ja0103e
      MYSQL_DATABASE: sped
      MYSQL_USER: neogrid
      MYSQL_PASSWORD: Ja0103e
    ports:
      - "6033:3306"
    volumes:
      - D:\DockerCompose\MySQLVolumes:/var/lib/mysql