version: "3"
name: SonarQube
services:
  sonarqube:
    image: sonarqube:community
    container_name: SonarQube
    depends_on:
      - db
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://db:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    volumes:
      - D:\DockerCompose\SonarQube\SonarQube\data:/opt/sonarqube/data
      - D:\DockerCompose\SonarQube\SonarQube\extensions:/opt/sonarqube/extensions
      - D:\DockerCompose\SonarQube\SonarQube\logs:/opt/sonarqube/logs
    ports:
      - "9000:9000"
  db:
    image: postgres:12
    container_name: Postgres12
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
    ports:
      - "5432:5432"
    volumes:
      - D:\DockerCompose\SonarQube\PostgeSQL:/var/lib/postgresql
      - D:\DockerCompose\SonarQube\PostgeSQL\data:/var/lib/postgresql/data